# Site Settings
title: gem5 (中文)
description: gem5 模拟器官方中文文档
lang: zh-CN
sourceurl: "https://gem5.googlesource.com/public/gem5-website/+/refs/heads/stable/README.md"
url: "https://www.gem5.org/"

# Build Settings
sass:
  sass_dir: _sass

include: ['_pages', '_pages/documentation/general_docs/stdlib_api/_static']

kramdown:
  input: GFM
  toc_levels: "1,2"
  auto_id: true

collections:
  pages:
    output: true
  bootcamp:
    output: true
    permalink: /bootcamp/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "_bootcamp"
      type: "bootcamp"
    values:
      layout: "bootcamp"
